services:
  feizai-admin:
    build: .
    container_name: feizai-admin
    restart: always
    ports:
      - "8088:8080"
    logging:
      #limit logs to 200MB (4rotations of 50M each)
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"
